@isTest
public class Test_Attorney_AsyncLeadtracNetClient {
    
    @isTest static void testEchoString() {              
        
        Test.startTest ();
            AsyncLeadtracNetClient.SearchByStatusHistoryResponse_elementFuture creditbyvendorelement = new AsyncLeadtracNetClient.SearchByStatusHistoryResponse_elementFuture ();
            try {
                creditbyvendorelement.getValue ();
            } catch (Exception e) {}
            AsyncLeadtracNetClient.GetClientsByPhoneNumberResponse_elementFuture debtsrespeelement = new AsyncLeadtracNetClient.GetClientsByPhoneNumberResponse_elementFuture ();
            try {
                debtsrespeelement.getValue ();
            } catch (Exception e) {}
            
            AsyncLeadtracNetClient.GetStatusListForWorkflowResponse_elementFuture creditorrespelement= new AsyncLeadtracNetClient.GetStatusListForWorkflowResponse_elementFuture ();
            try {
                creditorrespelement.getValue ();
            } catch (Exception e) {}
            
            AsyncLeadtracNetClient.CreateAppointmentResponse_elementFuture logentry = new AsyncLeadtracNetClient.CreateAppointmentResponse_elementFuture ();
            try {
                logEntry.getValue ();
            } catch (Exception e) {}
            
            AsyncLeadtracNetClient.GetScheduledAppointmentsResponse_elementFuture statusaudresp = new AsyncLeadtracNetClient.GetScheduledAppointmentsResponse_elementFuture ();
            try {
                statusaudresp.getValue ();
            } catch (Exception e) {}
            
            AsyncLeadtracNetClient.GetClientsResponse_elementFuture planhistresp = new AsyncLeadtracNetClient.GetClientsResponse_elementFuture ();
            try {
                planhistresp.getValue ();
            } catch (Exception e) {}
            
            AsyncLeadtracNetClient.GetClientsInStatusWithLimitResponse_elementFuture accntstatusresp = new AsyncLeadtracNetClient.GetClientsInStatusWithLimitResponse_elementFuture ();
            try {    
                accntstatusresp.getValue ();
            } catch (Exception e) {}
            
            AsyncLeadtracNetClient.SearchByStatusResponse_elementFuture taskrespele = new AsyncLeadtracNetClient.SearchByStatusResponse_elementFuture ();
            try {
                taskrespele.getValue ();
            } catch (Exception e) {}
            
            AsyncLeadtracNetClient.GetPropertyListResponse_elementFuture negotiatestatusresp = new AsyncLeadtracNetClient.GetPropertyListResponse_elementFuture ();   
            try {
                negotiatestatusresp.getValue ();
            } catch (Exception e) {}
            
            AsyncLeadtracNetClient.ChangeStatusByPropertyResponse_elementFuture modifieddebtresp = new AsyncLeadtracNetClient.ChangeStatusByPropertyResponse_elementFuture ();
            try {
                modifieddebtresp.getValue ();
            } catch (Exception e) {}
            
            AsyncLeadtracNetClient.GetUpdatedClientsWithChangesResponse_elementFuture debtsRespElement = new AsyncLeadtracNetClient.GetUpdatedClientsWithChangesResponse_elementFuture ();
            try {
                debtsRespElement.getValue ();
            } catch (Exception e) {}
            
            AsyncLeadtracNetClient.GetClientsInStatusResponse_elementFuture debtsRespElement1 = new AsyncLeadtracNetClient.GetClientsInStatusResponse_elementFuture ();
            try {
                debtsRespElement1.getValue ();
            } catch (Exception e) {}
            
            AsyncLeadtracNetClient.CancelAppointmentResponse_elementFuture debtsRespElement2 = new AsyncLeadtracNetClient.CancelAppointmentResponse_elementFuture();
            try {
                debtsRespElement2.getValue ();
            } catch (Exception e) {}
            
            AsyncLeadtracNetClient.ChangeClientStatusResponse_elementFuture debtsRespElement3 = new AsyncLeadtracNetClient.ChangeClientStatusResponse_elementFuture ();
            try {
                debtsRespElement3.getValue ();
            } catch (Exception e) {}
            
            AsyncLeadtracNetClient.AddLogEntryResponse_elementFuture debtsRespElement4 = new AsyncLeadtracNetClient.AddLogEntryResponse_elementFuture ();
            try {
                debtsRespElement4.getValue ();
            } catch (Exception e) {}
            
            AsyncLeadtracNetClient.SearchByStatusAuditResponse_elementFuture debtsRespElement5 = new AsyncLeadtracNetClient.SearchByStatusAuditResponse_elementFuture ();
            try {
                debtsRespElement5.getValue ();
            } catch (Exception e) {}
            
            AsyncLeadtracNetClient.GetClientResponse_elementFuture debtsRespElement6 = new AsyncLeadtracNetClient.GetClientResponse_elementFuture ();
            try {
                debtsRespElement6.getValue ();
            } catch (Exception e) {}
            
            AsyncLeadtracNetClient.SearchByPropertyResponse_elementFuture debtsRespElement7 = new AsyncLeadtracNetClient.SearchByPropertyResponse_elementFuture();
            try {
                debtsRespElement7.getValue ();
            } catch (Exception e) {}
            
            AsyncLeadtracNetClient.GetUpdatedClientsResponse_elementFuture debtsRespElement8 = new AsyncLeadtracNetClient.GetUpdatedClientsResponse_elementFuture ();
            try {
                debtsRespElement8.getValue ();
            } catch (Exception e) {}
            
            AsyncLeadtracNetClient.GetLogEntriesResponse_elementFuture debtsRespElement9 = new AsyncLeadtracNetClient.GetLogEntriesResponse_elementFuture ();
            try {
                debtsRespElement9.getValue ();
            } catch (Exception e) {}
            
            AsyncLeadtracNetClient.GetTaskTypesResponse_elementFuture taskTypeElement = new AsyncLeadtracNetClient.GetTaskTypesResponse_elementFuture ();
            try {
                taskTypeElement.getValue ();
            } catch (Exception e) {}
            
            AsyncLeadtracNetClient.GetTasksResponse_elementFuture taskRespElement = new AsyncLeadtracNetClient.GetTasksResponse_elementFuture ();
            try {
                taskRespElement.getValue ();
            } catch (Exception e) {}
            
            AsyncLeadtracNetClient.ValidateFormsResponse_elementFuture validateRespElement = new AsyncLeadtracNetClient.ValidateFormsResponse_elementFuture ();
            try {
                validateRespElement.getValue ();
            } catch (Exception e) {}
            
            AsyncLeadtracNetClient.GetCampaignListResponse_elementFuture campaignRespElement = new AsyncLeadtracNetClient.GetCampaignListResponse_elementFuture ();
            try {
                campaignRespElement.getValue ();
            } catch (Exception e) {}
            
            AsyncLeadtracNetClient.CreateTaskResponse_elementFuture tRespElement = new AsyncLeadtracNetClient.CreateTaskResponse_elementFuture ();
            try {
                tRespElement.getValue ();
            } catch (Exception e) {}
            
            AsyncLeadtracNetClient.AddNoteResponse_elementFuture addRespElement = new AsyncLeadtracNetClient.AddNoteResponse_elementFuture ();
            try {
                addRespElement.getValue ();
            } catch (Exception e) {}
            
            AsyncLeadtracNetClient.GetCompanyLogEntriesResponse_elementFuture logRespElement = new AsyncLeadtracNetClient.GetCompanyLogEntriesResponse_elementFuture ();
            try {
                logRespElement.getValue ();
            } catch (Exception e) {}
            
            AsyncLeadtracNetClient.ClearClientsFromQueueResponse_elementFuture queueRespElement = new AsyncLeadtracNetClient.ClearClientsFromQueueResponse_elementFuture ();
            try {
                queueRespElement.getValue ();
            } catch (Exception e) {}
            
            AsyncLeadtracNetClient.GetClientsInQueueResponse_elementFuture clientsqueueRespElement = new AsyncLeadtracNetClient.GetClientsInQueueResponse_elementFuture();
            try {
                clientsqueueRespElement.getValue ();
            } catch (Exception e) {}
            
            AsyncLeadtracNetClient.CreateOrUpdateClientResponse_elementFuture clientsCreateRespElement = new AsyncLeadtracNetClient.CreateOrUpdateClientResponse_elementFuture ();
            try {
                clientsCreateRespElement.getValue ();
            } catch (Exception e) {}
            
            AsyncLeadtracNetClient.GetLogCategoriesResponse_elementFuture logCategoriesRespElement = new AsyncLeadtracNetClient.GetLogCategoriesResponse_elementFuture ();
            try {
                logCategoriesRespElement.getValue ();
            } catch (Exception e) {}
            
            AsyncLeadtracNetClient.SearchByPhoneResponse_elementFuture searchPhoneRespElement = new AsyncLeadtracNetClient.SearchByPhoneResponse_elementFuture ();
            try {
                searchPhoneRespElement.getValue ();
            } catch (Exception e) {}
            
            AsyncLeadtracNetClient.GetStatusListResponse_elementFuture statusListRespElement = new AsyncLeadtracNetClient.GetStatusListResponse_elementFuture ();
            try {
                statusListRespElement.getValue ();
            } catch (Exception e) {}
            
            System.Continuation continuation = new Continuation (10);
            AsyncLeadtracNetClient.AsyncClientServiceSoap obj = new AsyncLeadtracNetClient.AsyncClientServiceSoap ();
            obj.beginSearchByStatusHistory (continuation, 'test', 'test', 'test', 1);
            obj.beginGetClientsByPhoneNumber (continuation, 'test', 'test', 'test');
            obj.beginGetStatusListForWorkflow (continuation, 'test', 'test', 'test');
            obj.beginCreateAppointment (continuation, 'test', 'test', 'test', 'test', new leadtracNetClient.AppointmentReservation ());
            obj.beginGetScheduledAppointments (continuation, 'test', 'test', 'test', System.now (), System.Now ());
            obj.beginGetClients (continuation, 'test', 'test', new leadtracNetClient.ArrayOfString (), new leadtracNetClient.ArrayOfString ());
            obj.beginGetClientsInStatusWithLimit (continuation, 'test', 'test', 1, new leadtracNetClient.ArrayOfString (), 0);
            obj.beginSearchByStatus (continuation, 'test', 'test', 1);
            obj.beginGetPropertyList (continuation, 'test', 'test', 'test');
            obj.beginChangeStatusByProperty (continuation, 'test', 'test', 'test', new leadtracNetClient.ArrayOfString (), 1);
            obj.beginGetUpdatedClientsWithChanges (continuation, 'test', 'test', System.now (), System.now ());
            obj.beginGetClientsInStatus (continuation, 'test', 'test', 1, new leadtracNetClient.ArrayOfString ());
            obj.beginCancelAppointment (continuation, 'test', 'test', 'test', 1);
            obj.beginChangeClientStatus (continuation, 'test', 'test', new leadtracNetClient.ArrayOfString (), 1);
            obj.beginAddLogEntry (continuation, 'test', 'test', 'test', new leadtracNetClient.LogEntry ());
            obj.beginSearchByStatusAudit (continuation, 'test', 'test', 1, System.now (), System.now ());
            obj.beginGetClient (continuation, 'test', 'test', 'test', new leadtracNetClient.ArrayOfString ());
            obj.beginSearchByProperty (continuation, 'test', 'test', 'test', 'test');
            obj.beginGetUpdatedClients (continuation, 'test', 'test', System.now (), System.now ());
            obj.beginGetLogEntries (continuation, 'test', 'test', 'test', System.now (), System.now ());
            obj.beginGetTaskTypes (continuation, 'test', 'test');
     //m       obj.beginGetTasks (continuation, 'test', 'test', new leadtracNetClient.ArrayOfString (), System.now (), System.Now ());
               obj.beginGetTasks (continuation, 'test', 'test', new leadtracNetClient.ArrayOfString ());

            obj.beginValidateForms (continuation, 'test', 'test', 'test');
            obj.beginGetCampaignList (continuation, 'test', 'test'); 
            obj.beginCreateTask (continuation, 'test', 'test', 1, 'test', 'test', 'test', System.now (), 1, 'test');
            obj.beginAddNote (continuation, 'test', 'test', 'test', System.now (), 'test');
            obj.beginGetCompanyLogEntries (continuation, 'test', 'test', System.Now (), System.now (), 1);
            obj.beginClearClientsFromQueue (continuation, 'test', 'test', new leadtracNetClient.ArrayOfString ());
            obj.beginGetClientsInQueue (continuation, 'test', 'test', new leadtracNetClient.ArrayOfString ());
            obj.beginCreateOrUpdateClient (continuation, 'test', 'test', 'test', new leadtracNetClient.ArrayOfClientProperty ());
            obj.beginGetLogCategories (continuation, 'test', 'test');
            obj.beginSearchByPhone (continuation, 'test', 'test', 'test');
            obj.beginGetStatusList (continuation, 'test', 'test');
        Test.stopTest ();
        
    }
}